### PR TITLE
Add pseudo-constructors to controller classes

### PR DESCRIPTION
**Pull request by kieranajp**
This allows you to add a `protected function setUp()` to your controller class, to call on initialisation.

### CODE REVIEW

**Comment by acelaya** [comment]
Wouldn't be the same to just override the constructor in your concrete controller and do something like this?

```php
class MyController extends \SlimController\SlimController
{
    public function __construct($app)
    {
        parent::__construct($app);
        $this->setUp();
    }

    public function setUp()
    {
        // Do stuff...
    }
}
```

This way there is no need to perform the same check if you don't have to call to `setUp()`

**Comment by kieranajp** [comment]
True, and I was already doing something like that, however I was doing the
same thing in a whole bunch of controllers. This was mainly to avoid that
repetition.

--Kieran
kieranajp.co.uk

**Comment by acelaya** [comment]
You could define your own abstract controller between SlimController and
your concrete controllers with that behavior.

However, if this was finally merged, instead of checking if the method
exists, I would define it empty so that it can be overridden.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by kieranajp** [comment]
Understood. Thanks for the review; I'll make that tweak when I'm not on
mobile and then you can decide whether to merge or not :)

-- Kieran
kieranajp.co.uk

**Comment by yaworsw** [comment]
I think @acelaya has the right idea here.

I recommend having an abstract controller class which inherits from `SlimController\SlimController` where you can put this sort of initialization.

On a somewhat related node I also recommend having an application class which inherits from `\SlimController\Slim` where app initialization can be done.

**Pull request closed without merging**
